### ISSUE TITLE
Error in render when v-model is null

### ISSUE THREAD

**Issue by Meshz** [alexurquhart/vue-bootstrap-typeahead#18]
Hello,

Several errors are showing up when the v-model of the component is equal to `null`. For now I can avoid this value but I thought you should be aware of.

`[Vue warn]: Error in render: "TypeError: Cannot read property 'length' of null" found in <VueBootstrapTypeaheadList> at vue-bootstrap-typeahead/src/components/VueBootstrapTypeaheadList.vue`
`TypeError: Cannot read property 'length' of null at VueComponent.matchedItems`
`[Vue warn]: Error in mounted hook: "TypeError: Failed to execute 'observe' on 'ResizeObserver': parameter 1 is not of type 'Element'." found in <VueBootstrapTypehead> at vue-bootstrap-typeahead/src/components/VueBootstrapTypeahead.vue`
`TypeError: Failed to execute 'observe' on 'ResizeObserver': parameter 1 is not of type 'Element' at VueComponent.mounted`
`Uncaught TypeError: Cannot set property 'width' of undefined at VueComponent.resizeList`

**Comment by alexurquhart** [comment]
Thanks!

Just pushed a patch, should be fixed now

**Comment by stefandunn** [comment]
I still encounter this on `0.2.6`. Has the npm package been updated with this fix?
